import { router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ApiError } from '../../src/api/client';
import { authApi } from '../../src/auth/authApi';
import { useAuthStore } from '../../src/auth/authStore';
import { MaterialIcon } from '../../src/components/MaterialIcon';
import { PinInput } from '../../src/components/PinInput';
import { colors, fonts } from '../../src/theme/colors';

export default function PinScreen() {
  const refreshSession = useAuthStore((state) => state.refreshSession); const [pin, setPin] = useState(''); const [confirmation, setConfirmation] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async () => { if (pin.length !== 4 || pin !== confirmation) { setError('Enter matching four-digit PINs.'); return; } setBusy(true); setError(''); try { await authApi.setTransactionPin(pin); await refreshSession(); router.replace('/(tabs)'); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Unable to create your PIN.'); } finally { setBusy(false); } };
  const ready = pin.length === 4 && confirmation.length === 4;
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.screen}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.icon}><MaterialIcon color={colors.primary} name="shield_lock" size={30} /></View><Text style={styles.eyebrow}>SECURE YOUR PAYMENTS</Text><Text style={styles.title}>Create transaction PIN</Text><Text style={styles.subtitle}>Choose four digits you’ll remember. You will enter this PIN whenever you authorize a purchase.</Text><View style={styles.card}><PinInput autoFocus label="New transaction PIN" onChangeText={setPin} value={pin} /><PinInput label="Confirm transaction PIN" onChangeText={setConfirmation} style={styles.second} value={confirmation} /><View style={styles.tip}><MaterialIcon color={colors.warning} name="info" size={17} /><Text style={styles.tipText}>Avoid easy combinations such as 1234 or repeated digits.</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={busy || !ready} onPress={() => void submit()} style={[styles.button, (!ready || busy) && styles.disabled]}>{busy ? <ActivityIndicator color={colors.white} /> : <><Text style={styles.buttonText}>Create secure PIN</Text><MaterialIcon color={colors.white} name="arrow_forward" size={19} /></>}</Pressable></View></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { backgroundColor: colors.background, flex: 1 }, content: { flexGrow: 1, justifyContent: 'center', padding: 24 }, icon: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: 20, height: 58, justifyContent: 'center', marginBottom: 20, width: 58 }, eyebrow: { color: colors.primary, fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1.2 }, title: { color: colors.text, fontFamily: fonts.extraBold, fontSize: 29, letterSpacing: -0.8, marginTop: 7 }, subtitle: { color: colors.muted, fontFamily: fonts.regular, fontSize: 14, lineHeight: 21, marginTop: 9 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 22, borderWidth: 1, marginTop: 25, padding: 18 }, second: { marginTop: 16 }, tip: { alignItems: 'flex-start', backgroundColor: '#FFF8E8', borderRadius: 12, flexDirection: 'row', gap: 8, marginTop: 16, padding: 11 }, tipText: { color: colors.muted, flex: 1, fontFamily: fonts.medium, fontSize: 11, lineHeight: 16 }, error: { color: colors.danger, fontFamily: fonts.semiBold, fontSize: 12, marginTop: 12 }, button: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 14, flexDirection: 'row', gap: 8, justifyContent: 'center', marginTop: 20, minHeight: 54 }, disabled: { opacity: 0.45 }, buttonText: { color: colors.white, fontFamily: fonts.bold, fontSize: 14 } });
