import { useMutation, useQuery } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Screen } from '../../src/components/Screen';
import { useAuthStore } from '../../src/auth/authStore';
import { biometricLock } from '../../src/auth/biometricLock';
import { deviceApi } from '../../src/device/deviceApi';
import { colors } from '../../src/theme/colors';

export default function AccountScreen() {
  const user = useAuthStore((state) => state.user);
  const signOut = useAuthStore((state) => state.signOut);
  const [biometric, setBiometric] = useState(false);
  const preferences = useQuery({ queryKey: ['notification-preferences'], queryFn: async () => (await deviceApi.preferences()).data });
  const updatePreferences = useMutation({ mutationFn: deviceApi.updatePreferences, onSuccess: (response) => preferences.refetch().then(() => response) });
  useEffect(() => { void biometricLock.isEnabled().then(setBiometric); }, []);
  const toggleBiometric = async (enabled: boolean) => {
    if (enabled && !(await biometricLock.isAvailable())) { Alert.alert('Biometrics unavailable', 'Set up Face ID, Touch ID or fingerprint in your phone settings first.'); return; }
    if (enabled && !(await biometricLock.unlock())) return;
    await biometricLock.setEnabled(enabled); setBiometric(enabled);
  };
  return <Screen><Text style={styles.title}>Account</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.initial}>{user?.first_name?.[0]}{user?.last_name?.[0]}</Text></View><View><Text style={styles.name}>{user?.first_name} {user?.last_name}</Text><Text style={styles.email}>{user?.email}</Text></View></View><Pressable onPress={() => router.push('/edit-profile')} style={styles.edit}><Text style={styles.editText}>Edit profile</Text></Pressable><View style={styles.details}><Detail label="Username" value={`@${user?.username}`} /><Detail label="Phone" value={user?.phone_number ?? 'Not added'} /><Detail label="Phone verified" value={user?.phone_verified ? 'Yes' : 'No'} /></View><Text style={styles.section}>Security & notifications</Text><Pressable onPress={() => router.push('/security-settings')} style={styles.navigation}><Text style={styles.settingLabel}>Password and transaction PIN</Text><Text style={styles.arrow}>›</Text></Pressable><Setting label="Biometric unlock" value={biometric} onChange={(value) => void toggleBiometric(value)} /><Setting label="Transaction alerts" value={preferences.data?.transactional_enabled ?? true} onChange={(transactional_enabled) => updatePreferences.mutate({ transactional_enabled, promotional_enabled: preferences.data?.promotional_enabled ?? false })} /><Setting label="Offers and announcements" value={preferences.data?.promotional_enabled ?? false} onChange={(promotional_enabled) => updatePreferences.mutate({ transactional_enabled: preferences.data?.transactional_enabled ?? true, promotional_enabled })} /><Pressable onPress={() => router.push('/help')} style={styles.navigation}><Text style={styles.settingLabel}>Help, support and policies</Text><Text style={styles.arrow}>›</Text></Pressable><Pressable onPress={() => void signOut()} style={styles.logout}><Text style={styles.logoutText}>Sign out</Text></Pressable></Screen>;
}

function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }
function Setting({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <View style={styles.setting}><Text style={styles.settingLabel}>{label}</Text><Switch onValueChange={onChange} trackColor={{ true: '#86efac' }} thumbColor={value ? colors.primary : '#f4f4f5'} value={value} /></View>; }

const styles = StyleSheet.create({ title: { color: colors.text, fontSize: 30, fontWeight: '800', letterSpacing: -0.8 }, profile: { alignItems: 'center', flexDirection: 'row', marginTop: 24 }, avatar: { alignItems: 'center', backgroundColor: colors.primarySoft, borderColor: colors.border, borderRadius: 32, borderWidth: 1, height: 64, justifyContent: 'center', width: 64 }, initial: { color: colors.primary, fontSize: 20, fontWeight: '800' }, name: { color: colors.text, fontSize: 18, fontWeight: '800', letterSpacing: -0.3, marginLeft: 14 }, email: { color: colors.muted, fontSize: 11, marginLeft: 14, marginTop: 4 }, edit: { alignSelf: 'flex-start', backgroundColor: colors.primarySoft, borderRadius: 10, marginLeft: 78, marginTop: 8, paddingHorizontal: 10, paddingVertical: 6 }, editText: { color: colors.primary, fontSize: 10, fontWeight: '800' }, details: { backgroundColor: colors.surface, borderRadius: 20, elevation: 2, marginTop: 24, paddingHorizontal: 16, shadowColor: '#193E33', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.05, shadowRadius: 10 }, detail: { borderBottomColor: colors.border, borderBottomWidth: 1, paddingVertical: 15 }, detailLabel: { color: colors.muted, fontSize: 9, fontWeight: '700', letterSpacing: 0.7, textTransform: 'uppercase' }, detailValue: { color: colors.text, fontSize: 13, fontWeight: '700', marginTop: 5 }, section: { color: colors.text, fontSize: 17, fontWeight: '800', marginBottom: 10, marginTop: 25 }, setting: { alignItems: 'center', backgroundColor: colors.surface, borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 15 }, navigation: { alignItems: 'center', backgroundColor: colors.surface, borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 17 }, arrow: { color: colors.primary, fontSize: 24 }, settingLabel: { color: colors.text, fontSize: 13, fontWeight: '700' }, logout: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.danger, borderRadius: 15, borderWidth: 1, marginTop: 25, padding: 15 }, logoutText: { color: colors.danger, fontSize: 13, fontWeight: '800' } });
