import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { mobileApi } from '../../src/api/mobileApi';
import { useAuthStore } from '../../src/auth/authStore';
import { BrandLogo } from '../../src/components/BrandLogo';
import { MaterialIcon } from '../../src/components/MaterialIcon';
import { colors, fonts } from '../../src/theme/colors';

const money = (amount: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN' }).format(amount);
const services = [
  { label: 'Data', symbol: '⌁', tint: '#E0F5FF', slug: 'data' },
  { label: 'Airtime', symbol: '✦', tint: '#E5F8F0', slug: 'airtime' },
  { label: 'Cable TV', symbol: '▣', tint: '#F2EAFE', slug: 'cable_subscription' },
  { label: 'Electricity', symbol: 'ϟ', tint: '#FFF2D7', slug: 'utility_bills' },
];

export default function HomeScreen() {
  const user = useAuthStore((state) => state.user);
  const query = useQuery({ queryKey: ['dashboard'], queryFn: mobileApi.dashboard });
  const announcements = useQuery({ queryKey: ['announcements'], queryFn: mobileApi.announcements });
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [announcementsOpen, setAnnouncementsOpen] = useState(false);
  const [buyAgainOpen, setBuyAgainOpen] = useState(false);
  const [buyAgainSearch, setBuyAgainSearch] = useState('');
  const buyAgainPlans = query.data?.buy_again_plans ?? [];
  const filteredBuyAgainPlans = buyAgainPlans.filter((plan) => `${plan.plan_name} ${plan.provider}`.toLowerCase().includes(buyAgainSearch.trim().toLowerCase()));

  return (
    <SafeAreaView edges={['top']} style={styles.safe}>
      <ScrollView contentContainerStyle={styles.screen} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} tintColor={colors.primary} />}>
        <View style={styles.greetingRow}><View><Text style={styles.eyebrow}>WELCOME BACK</Text><Text style={styles.title}>Hi, {user?.first_name || 'there'} <Text style={styles.wave}>👋</Text></Text></View><View style={styles.headerActions}>{!!announcements.data?.length && <Pressable accessibilityLabel="Announcements" onPress={() => setAnnouncementsOpen(true)} style={styles.bell}><MaterialIcon color={colors.text} name="campaign" size={21} /><View style={styles.announcementDot} /></Pressable>}<Pressable accessibilityLabel="Notifications" onPress={() => setNotificationsOpen(true)} style={styles.bell}><MaterialIcon color={colors.text} name="notifications" size={21} /><View style={styles.unreadDot} /></Pressable><BrandLogo size={42} /></View></View>
        <View style={styles.walletCard}>
          <View style={styles.walletGlow} />
          <View style={styles.walletTop}><View><Text style={styles.walletLabel}>AVAILABLE BALANCE</Text>{query.isPending ? <ActivityIndicator color={colors.white} style={styles.loader} /> : <Text style={styles.balance}>{money(query.data?.wallet.balance ?? 0)}</Text>}</View><View style={styles.nairaBadge}><Text style={styles.naira}>₦</Text></View></View>
          <View style={styles.walletActions}><Pressable onPress={() => router.push('/wallet')} style={({ pressed }) => [styles.fundButton, pressed && styles.pressed]}><Text style={styles.fundPlus}>＋</Text><Text style={styles.fundText}>Add money</Text></Pressable><Pressable onPress={() => router.push('/transactions')} style={styles.walletLink}><Text style={styles.walletLinkText}>History  ›</Text></Pressable></View>
        </View>
        {query.isError && <Pressable onPress={() => void query.refetch()} style={styles.error}><Text style={styles.errorText}>Could not load your dashboard. Tap to retry.</Text></Pressable>}
        <View style={styles.headingRow}><Text style={styles.sectionTitle}>Quick services</Text><Pressable onPress={() => router.push('/services')}><Text style={styles.link}>See all</Text></Pressable></View>
        <View style={styles.serviceGrid}>{services.map((service) => <Pressable key={service.slug} onPress={() => router.push({ pathname: '/service/[slug]', params: { slug: service.slug, name: service.label } })} style={({ pressed }) => [styles.service, pressed && styles.pressed]}><View style={[styles.serviceIconBox, { backgroundColor: service.tint }]}><Text style={styles.serviceIcon}>{service.symbol}</Text></View><Text style={styles.serviceLabel}>{service.label}</Text></Pressable>)}</View>
        <Pressable onPress={() => setBuyAgainOpen(true)} style={({ pressed }) => [styles.buyAgainCard, pressed && styles.pressed]}><View style={styles.buyAgainIcon}><MaterialIcon color={colors.primary} name="replay" size={24} /></View><View style={styles.buyAgainCopy}><Text style={styles.buyAgainTitle}>Buy again</Text><Text style={styles.buyAgainText}>Repeat one of your recent data plans</Text></View><View style={styles.buyAgainArrow}><MaterialIcon color={colors.primary} name="arrow_forward" size={19} /></View></Pressable>
        <View style={styles.headingRow}><Text style={styles.sectionTitle}>Recent transactions</Text><Pressable onPress={() => router.push('/transactions')}><Text style={styles.link}>View all</Text></Pressable></View>
        <View style={styles.activityCard}>{query.data?.recent_transactions.length ? query.data.recent_transactions.map((item, index) => { const tone = item.status === 'successful' ? styles.transactionGood : item.status === 'failed' ? styles.transactionBad : styles.transactionWaiting; return <Pressable key={item.id} onPress={() => router.push({ pathname: '/transaction/[id]', params: { id: item.id } })} style={[styles.transaction, index === query.data!.recent_transactions.length - 1 && styles.lastTransaction]}><View style={[styles.transactionIcon, tone]}><MaterialIcon color={item.status === 'successful' ? colors.success : item.status === 'failed' ? colors.danger : colors.warning} name={item.status === 'successful' ? 'check' : item.status === 'failed' ? 'close' : 'schedule'} size={18} /></View><View style={styles.transactionInfo}><Text numberOfLines={1} style={styles.transactionTitle}>{item.description}</Text><Text style={styles.transactionBeneficiary}>{item.beneficiary ?? 'No beneficiary recorded'}</Text><Text style={styles.transactionMeta}>{new Date(item.created_at).toLocaleDateString()} · {item.status}</Text></View><Text style={[styles.amount, item.status === 'successful' ? styles.amountGood : item.status === 'failed' ? styles.amountBad : styles.amountWaiting]}>-{money(item.amount)}</Text></Pressable>; }) : !query.isPending && <Text style={styles.empty}>Your transactions will appear here.</Text>}</View>
      </ScrollView>
      <Modal animationType="fade" onRequestClose={() => setNotificationsOpen(false)} transparent visible={notificationsOpen}><View style={styles.modalRoot}><Pressable onPress={() => setNotificationsOpen(false)} style={styles.backdrop} /><View style={styles.sheet}><View style={styles.sheetHandle} /><View style={styles.sheetHeader}><View><Text style={styles.sheetTitle}>Notifications</Text><Text style={styles.sheetSubtitle}>Updates that matter to you</Text></View><Pressable onPress={() => setNotificationsOpen(false)} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={styles.notificationList}>{query.data?.recent_transactions.slice(0, 4).map((item) => <Pressable key={item.id} onPress={() => { setNotificationsOpen(false); router.push({ pathname: '/transaction/[id]', params: { id: item.id } }); }} style={styles.notification}><View style={[styles.notificationIcon, item.status === 'successful' ? styles.notificationGood : styles.notificationWait]}><Text style={styles.notificationIconText}>{item.status === 'successful' ? '✓' : '·'}</Text></View><View style={styles.notificationCopy}><Text numberOfLines={1} style={styles.notificationTitle}>{item.description}</Text><Text style={styles.notificationText}>{item.status === 'successful' ? 'Your transaction was completed successfully.' : `Transaction is ${item.status}.`}</Text><Text style={styles.notificationTime}>{new Date(item.created_at).toLocaleDateString()}</Text></View></Pressable>)}{!query.data?.recent_transactions.length && <View style={styles.noNotifications}><View style={styles.noNotificationsIcon}><Text style={styles.bellText}>♢</Text></View><Text style={styles.noNotificationsTitle}>You’re all caught up</Text><Text style={styles.noNotificationsText}>New payment and account updates will appear here.</Text></View>}</ScrollView></View></View></Modal>
      <Modal animationType="slide" onRequestClose={() => setBuyAgainOpen(false)} transparent visible={buyAgainOpen}><View style={styles.modalRoot}><Pressable onPress={() => setBuyAgainOpen(false)} style={styles.backdrop} /><View style={styles.buyAgainSheet}><View style={styles.sheetHandle} /><View style={styles.sheetHeader}><View><Text style={styles.sheetTitle}>Buy again</Text><Text style={styles.sheetSubtitle}>Choose a recent data plan to repeat</Text></View><Pressable onPress={() => setBuyAgainOpen(false)} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View>{buyAgainPlans.length > 0 && <View style={styles.searchShell}><MaterialIcon color={colors.muted} name="search" size={20} /><TextInput onChangeText={setBuyAgainSearch} placeholder="Search plan or network" placeholderTextColor={colors.muted} style={styles.searchInput} value={buyAgainSearch} /></View>}<ScrollView contentContainerStyle={styles.buyAgainList} keyboardShouldPersistTaps="handled">{filteredBuyAgainPlans.map((plan) => <Pressable key={plan.plan_id} onPress={() => { setBuyAgainOpen(false); setBuyAgainSearch(''); router.push({ pathname: '/checkout', params: { product: 'data', planId: plan.plan_id, planName: plan.plan_name, price: String(plan.price), provider: plan.provider } }); }} style={({ pressed }) => [styles.buyAgainPlan, pressed && styles.pressed]}><View style={styles.planNetwork}><MaterialIcon color={colors.primary} name="signal_cellular_alt" size={21} /></View><View style={styles.planCopy}><Text numberOfLines={1} style={styles.planName}>{plan.plan_name}</Text><Text style={styles.planMeta}>{plan.provider}</Text></View><Text style={styles.planPrice}>{money(plan.price)}</Text></Pressable>)}{buyAgainPlans.length === 0 && <View style={styles.buyAgainEmpty}><View style={styles.buyAgainEmptyIcon}><MaterialIcon color={colors.primary} name="history" size={30} /></View><Text style={styles.noNotificationsTitle}>Nothing to repeat yet</Text><Text style={styles.noNotificationsText}>Your successful data purchases will appear here for quick repurchase.</Text><Pressable onPress={() => { setBuyAgainOpen(false); router.push({ pathname: '/service/[slug]', params: { slug: 'data', name: 'Data' } }); }} style={styles.browseData}><Text style={styles.browseDataText}>Browse data plans</Text></Pressable></View>}{buyAgainPlans.length > 0 && filteredBuyAgainPlans.length === 0 && <Text style={styles.emptySearch}>No recent plan matches your search.</Text>}</ScrollView></View></View></Modal>
      <Modal animationType="fade" onRequestClose={() => setAnnouncementsOpen(false)} transparent visible={announcementsOpen}><View style={styles.modalCenter}><Pressable onPress={() => setAnnouncementsOpen(false)} style={styles.backdrop} /><View style={styles.announcementModal}><View style={styles.announcementHeader}><View style={styles.announcementMark}><MaterialIcon color={colors.primary} name="campaign" size={24} /></View><View style={styles.announcementHeaderCopy}><Text style={styles.sheetTitle}>Announcements</Text><Text style={styles.sheetSubtitle}>Latest updates from OresamSub</Text></View><Pressable onPress={() => setAnnouncementsOpen(false)} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={styles.announcementList}>{announcements.data?.map((announcement) => <View key={announcement.id} style={styles.announcementCard}><Text style={styles.announcementTitle}>{announcement.title}</Text><Text style={styles.announcementText}>{announcement.description}</Text><Text style={styles.announcementDate}>{new Date(announcement.created_at).toLocaleDateString()}</Text></View>)}</ScrollView></View></View></Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { backgroundColor: colors.background, flex: 1 }, screen: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 112 },
  greetingRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 }, eyebrow: { color: colors.primary, fontFamily: fonts.extraBold, fontSize: 10, letterSpacing: 1.5 }, title: { color: colors.text, fontFamily: fonts.extraBold, fontSize: 25, letterSpacing: -0.7, marginTop: 3 }, wave: { fontSize: 21 }, headerActions: { alignItems: 'center', flexDirection: 'row', gap: 7 }, bell: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: 20, height: 40, justifyContent: 'center', width: 40 }, bellText: { color: colors.text, fontFamily: fonts.extraBold, fontSize: 20 }, unreadDot: { backgroundColor: colors.accent, borderColor: colors.surface, borderRadius: 5, borderWidth: 2, height: 9, position: 'absolute', right: 7, top: 6, width: 9 }, announcementDot: { backgroundColor: colors.danger, borderColor: colors.surface, borderRadius: 5, borderWidth: 2, height: 9, position: 'absolute', right: 7, top: 6, width: 9 }, avatar: { alignItems: 'center', backgroundColor: colors.primarySoft, borderColor: '#C3ECDD', borderRadius: 22, borderWidth: 1, height: 44, justifyContent: 'center', width: 44 }, avatarText: { color: colors.primaryDark, fontFamily: fonts.extraBold, fontSize: 17 },
  walletCard: { backgroundColor: colors.primaryDark, borderRadius: 24, overflow: 'hidden', paddingHorizontal: 20, paddingVertical: 18, shadowColor: colors.primaryDark, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 18, elevation: 8 }, walletGlow: { backgroundColor: '#159570', borderRadius: 100, height: 150, opacity: 0.42, position: 'absolute', right: -45, top: -65, width: 150 }, walletTop: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' }, walletLabel: { color: '#A7DCCB', fontFamily: fonts.extraBold, fontSize: 10, letterSpacing: 1.1 }, balance: { color: colors.white, fontFamily: fonts.extraBold, fontSize: 27, letterSpacing: -0.8, marginTop: 6 }, loader: { alignSelf: 'flex-start', marginVertical: 10 }, nairaBadge: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.13)', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }, naira: { color: colors.white, fontFamily: fonts.extraBold, fontSize: 18 }, walletActions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 }, fundButton: { alignItems: 'center', backgroundColor: colors.white, borderRadius: 12, flexDirection: 'row', paddingHorizontal: 13, paddingVertical: 9 }, fundPlus: { color: colors.primaryDark, fontFamily: fonts.extraBold, fontSize: 16, marginRight: 4 }, fundText: { color: colors.primaryDark, fontFamily: fonts.extraBold, fontSize: 12 }, walletLink: { padding: 8 }, walletLinkText: { color: '#CDECE2', fontFamily: fonts.bold, fontSize: 12 }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  error: { backgroundColor: '#FFF0F0', borderRadius: 12, marginTop: 12, padding: 12 }, errorText: { color: colors.danger, fontFamily: fonts.regular }, headingRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 13, marginTop: 24 }, sectionTitle: { color: colors.text, fontFamily: fonts.extraBold, fontSize: 17, letterSpacing: -0.3 }, link: { color: colors.primary, fontFamily: fonts.bold, fontSize: 12 },
  serviceGrid: { flexDirection: 'row', gap: 9 }, service: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: 18, elevation: 2, flex: 1, paddingBottom: 13, paddingTop: 11, shadowColor: '#193E33', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.05, shadowRadius: 10 }, serviceIconBox: { alignItems: 'center', borderRadius: 14, height: 42, justifyContent: 'center', width: 42 }, serviceIcon: { color: colors.primaryDark, fontFamily: fonts.extraBold, fontSize: 21 }, serviceLabel: { color: colors.text, fontFamily: fonts.bold, fontSize: 10, marginTop: 7 },
  buyAgainCard: { alignItems: 'center', backgroundColor: colors.primarySoft, borderColor: '#C7ECDD', borderRadius: 18, borderWidth: 1, flexDirection: 'row', marginTop: 14, padding: 14 }, buyAgainIcon: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: 14, height: 44, justifyContent: 'center', width: 44 }, buyAgainCopy: { flex: 1, marginHorizontal: 12 }, buyAgainTitle: { color: colors.primaryDark, fontFamily: fonts.extraBold, fontSize: 14 }, buyAgainText: { color: colors.muted, fontFamily: fonts.medium, fontSize: 10, marginTop: 3 }, buyAgainArrow: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: 15, height: 30, justifyContent: 'center', width: 30 },
  activityCard: { backgroundColor: colors.surface, borderRadius: 20, elevation: 2, overflow: 'hidden', shadowColor: '#193E33', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.05, shadowRadius: 12 }, transaction: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', padding: 14 }, lastTransaction: { borderBottomWidth: 0 }, transactionIcon: { alignItems: 'center', borderRadius: 13, height: 38, justifyContent: 'center', marginRight: 11, width: 38 }, transactionGood: { backgroundColor: '#E9F9F1' }, transactionBad: { backgroundColor: '#FFF0F0' }, transactionWaiting: { backgroundColor: '#FFF7E5' }, transactionIconText: { color: colors.primary, fontFamily: fonts.extraBold, fontSize: 17 }, transactionInfo: { flex: 1 }, transactionTitle: { color: colors.text, fontFamily: fonts.bold, fontSize: 13 }, transactionBeneficiary: { color: colors.text, fontFamily: fonts.semiBold, fontSize: 10, marginTop: 3 }, transactionMeta: { color: colors.muted, fontFamily: fonts.regular, fontSize: 9, marginTop: 3, textTransform: 'capitalize' }, amount: { fontFamily: fonts.extraBold, fontSize: 11 }, amountGood: { color: colors.success }, amountBad: { color: colors.danger }, amountWaiting: { color: colors.warning }, empty: { color: colors.muted, fontFamily: fonts.regular, paddingVertical: 24, textAlign: 'center' },
  modalRoot: { flex: 1, justifyContent: 'flex-end' }, backdrop: { backgroundColor: 'rgba(5, 20, 15, 0.5)', bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 }, sheet: { backgroundColor: colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: '72%', minHeight: 360, paddingBottom: 28, paddingHorizontal: 20 }, sheetHandle: { alignSelf: 'center', backgroundColor: '#C8D5D0', borderRadius: 3, height: 5, marginBottom: 18, marginTop: 10, width: 42 }, sheetHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, sheetTitle: { color: colors.text, fontSize: 23, fontWeight: '800', letterSpacing: -0.6 }, sheetSubtitle: { color: colors.muted, fontSize: 11, marginTop: 3 }, close: { alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: 17, height: 34, justifyContent: 'center', width: 34 }, closeText: { color: colors.text, fontSize: 23, marginTop: -2 }, notificationList: { gap: 10, paddingTop: 18 }, notification: { alignItems: 'flex-start', backgroundColor: colors.surface, borderRadius: 18, flexDirection: 'row', padding: 14 }, notificationIcon: { alignItems: 'center', borderRadius: 15, height: 42, justifyContent: 'center', marginRight: 12, width: 42 }, notificationGood: { backgroundColor: colors.primarySoft }, notificationWait: { backgroundColor: '#FFF2D7' }, notificationIconText: { color: colors.primaryDark, fontSize: 17, fontWeight: '800' }, notificationCopy: { flex: 1 }, notificationTitle: { color: colors.text, fontSize: 12, fontWeight: '800' }, notificationText: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, notificationTime: { color: '#96A49F', fontSize: 9, marginTop: 5 }, noNotifications: { alignItems: 'center', paddingHorizontal: 30, paddingTop: 44 }, noNotificationsIcon: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: 24, height: 52, justifyContent: 'center', width: 52 }, noNotificationsTitle: { color: colors.text, fontSize: 14, fontWeight: '800', marginTop: 14 }, noNotificationsText: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 5, textAlign: 'center' },
  buyAgainSheet: { backgroundColor: colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: '82%', minHeight: 430, paddingBottom: 28, paddingHorizontal: 20 }, searchShell: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, flexDirection: 'row', marginTop: 18, paddingHorizontal: 13 }, searchInput: { color: colors.text, flex: 1, fontFamily: fonts.medium, fontSize: 13, paddingHorizontal: 9, paddingVertical: 13 }, buyAgainList: { gap: 10, paddingBottom: 16, paddingTop: 14 }, buyAgainPlan: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 17, borderWidth: 1, flexDirection: 'row', padding: 13 }, planNetwork: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: 13, height: 42, justifyContent: 'center', marginRight: 11, width: 42 }, planCopy: { flex: 1, marginRight: 8 }, planName: { color: colors.text, fontFamily: fonts.bold, fontSize: 12 }, planMeta: { color: colors.muted, fontFamily: fonts.regular, fontSize: 9, marginTop: 4 }, planPrice: { color: colors.primary, fontFamily: fonts.extraBold, fontSize: 11 }, buyAgainEmpty: { alignItems: 'center', paddingHorizontal: 25, paddingTop: 38 }, buyAgainEmptyIcon: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: 27, height: 56, justifyContent: 'center', width: 56 }, browseData: { backgroundColor: colors.primary, borderRadius: 12, marginTop: 18, paddingHorizontal: 17, paddingVertical: 11 }, browseDataText: { color: colors.white, fontFamily: fonts.bold, fontSize: 12 }, emptySearch: { color: colors.muted, fontFamily: fonts.medium, paddingVertical: 35, textAlign: 'center' },
  modalCenter: { flex: 1, justifyContent: 'center', padding: 20 }, announcementModal: { backgroundColor: colors.background, borderRadius: 25, maxHeight: '72%', padding: 18 }, announcementHeader: { alignItems: 'center', flexDirection: 'row' }, announcementMark: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: 14, height: 42, justifyContent: 'center', marginRight: 10, width: 42 }, announcementHeaderCopy: { flex: 1 }, announcementList: { gap: 10, paddingTop: 17 }, announcementCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, padding: 14 }, announcementTitle: { color: colors.text, fontFamily: fonts.extraBold, fontSize: 13 }, announcementText: { color: colors.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 17, marginTop: 6 }, announcementDate: { color: colors.primary, fontFamily: fonts.bold, fontSize: 9, marginTop: 9 },
});
