import { useInfiniteQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { mobileApi } from '../../src/api/mobileApi';
import type { MobileTransaction } from '../../src/api/types';
import { MaterialIcon } from '../../src/components/MaterialIcon';
import { colors, fonts } from '../../src/theme/colors';

const money = (amount: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN' }).format(amount);

export default function TransactionsScreen() {
  const query = useInfiniteQuery({ queryKey: ['transactions'], initialPageParam: 1, queryFn: ({ pageParam }) => mobileApi.transactions(pageParam), getNextPageParam: (last) => last.meta.current_page < last.meta.last_page ? last.meta.current_page + 1 : undefined });
  const items = query.data?.pages.flatMap((page) => page.items) ?? [];
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Text style={styles.title}>Transactions</Text><Text style={styles.subtitle}>Your payments and their current status</Text></View><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} tintColor={colors.primary} />} renderItem={({ item }) => <TransactionRow item={item} />} onEndReached={() => query.hasNextPage && !query.isFetchingNextPage && void query.fetchNextPage()} onEndReachedThreshold={0.4} ListEmptyComponent={query.isPending ? <ActivityIndicator color={colors.primary} style={styles.loading} /> : query.isError ? <Pressable onPress={() => void query.refetch()}><Text style={styles.empty}>Could not load transactions. Tap to retry.</Text></Pressable> : <Text style={styles.empty}>No transactions yet.</Text>} ListFooterComponent={query.isFetchingNextPage ? <ActivityIndicator color={colors.primary} /> : null} /></SafeAreaView>;
}

function TransactionRow({ item }: { item: MobileTransaction }) { const color = item.status === 'successful' ? colors.success : item.status === 'failed' ? colors.danger : colors.warning; return <Pressable onPress={() => router.push({ pathname: '/transaction/[id]', params: { id: item.id } })} style={styles.row}><View style={[styles.icon, { backgroundColor: `${color}16` }]}><MaterialIcon color={color} name={item.status === 'successful' ? 'check' : item.status === 'failed' ? 'close' : 'schedule'} size={18} /></View><View style={styles.copy}><Text style={styles.name}>{item.description}</Text><Text style={styles.beneficiary}>{item.beneficiary ?? 'No beneficiary recorded'}</Text><Text style={styles.meta}>{new Date(item.created_at).toLocaleString()}</Text></View><View><Text style={[styles.amount, { color }]}>{money(item.amount)}</Text><Text style={[styles.badge, { color }]}>{item.status}</Text></View></Pressable>; }

const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, header: { paddingHorizontal: 20, paddingTop: 14 }, title: { color: colors.text, fontFamily: fonts.extraBold, fontSize: 30, letterSpacing: -0.8 }, subtitle: { color: colors.muted, fontFamily: fonts.regular, fontSize: 13, marginTop: 5 }, list: { flexGrow: 1, gap: 9, padding: 20, paddingBottom: 112 }, row: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: 17, elevation: 2, flexDirection: 'row', padding: 13, shadowColor: '#193E33', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.05, shadowRadius: 10 }, icon: { alignItems: 'center', borderRadius: 13, height: 40, justifyContent: 'center', marginRight: 11, width: 40 }, copy: { flex: 1, marginRight: 10 }, name: { color: colors.text, fontFamily: fonts.bold, fontSize: 12 }, beneficiary: { color: colors.text, fontFamily: fonts.semiBold, fontSize: 10, marginTop: 3 }, meta: { color: colors.muted, fontFamily: fonts.regular, fontSize: 8, marginTop: 3 }, amount: { fontFamily: fonts.extraBold, fontSize: 11, textAlign: 'right' }, badge: { fontFamily: fonts.bold, fontSize: 8, marginTop: 5, textAlign: 'right', textTransform: 'uppercase' }, loading: { marginTop: 50 }, empty: { color: colors.muted, padding: 40, textAlign: 'center' } });
