import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { mobileApi } from '../../src/api/mobileApi';
import { Screen } from '../../src/components/Screen';
import { colors } from '../../src/theme/colors';

const money = (amount: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN' }).format(amount);

export default function WalletScreen() {
  const wallet = useQuery({ queryKey: ['wallet'], queryFn: mobileApi.wallet });
  const accounts = useQuery({ queryKey: ['wallet-accounts'], queryFn: mobileApi.walletAccounts });
  const history = useQuery({ queryKey: ['funding-history'], queryFn: mobileApi.fundingHistory });
  return <Screen><Text style={styles.eyebrow}>YOUR MONEY</Text><Text style={styles.title}>Wallet</Text><View style={styles.card}><View style={styles.cardOrb} /><Text style={styles.label}>TOTAL AVAILABLE</Text>{wallet.isPending ? <ActivityIndicator color={colors.white} style={styles.loading} /> : <Text style={styles.balance}>{money(wallet.data?.balance ?? 0)}</Text>}<Text style={styles.cardNote}>Ready for bills and airtime</Text></View><View style={styles.sectionRow}><Text style={styles.section}>Bank accounts</Text></View>{accounts.isPending ? <ActivityIndicator color={colors.primary} /> : accounts.data?.length ? accounts.data.map((account) => <Pressable key={account.id} style={styles.account}><View><Text style={styles.bank}>{account.bank_name}</Text><Text style={styles.accountName}>{account.account_name}</Text></View><Text selectable style={styles.number}>{account.account_number}</Text></Pressable>) : <View style={styles.emptyCard}><Text style={styles.empty}>No bank account is available yet.</Text></View>}<Text style={styles.section}>Recent funding</Text><View style={styles.historyCard}>{history.data?.length ? history.data.slice(0, 5).map((item) => <View key={item.id} style={styles.history}><View><Text style={styles.bank}>{item.bank_name}</Text><Text style={styles.accountName}>{new Date(item.created_at).toLocaleDateString()} · {item.status}</Text></View><Text style={styles.credit}>+{money(item.amount_settled)}</Text></View>) : !history.isPending && <Text style={styles.empty}>No wallet funding yet.</Text>}</View></Screen>;
}

const styles = StyleSheet.create({ eyebrow: { color: colors.primary, fontSize: 10, fontWeight: '800', letterSpacing: 1.4, marginTop: 4 }, title: { color: colors.text, fontSize: 30, fontWeight: '800', letterSpacing: -0.8, marginBottom: 18, marginTop: 2 }, card: { backgroundColor: colors.primaryDark, borderRadius: 24, overflow: 'hidden', padding: 20, shadowColor: colors.primaryDark, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 18, elevation: 8 }, cardOrb: { backgroundColor: '#159570', borderRadius: 90, height: 150, opacity: 0.4, position: 'absolute', right: -45, top: -70, width: 150 }, label: { color: '#A7DCCB', fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, balance: { color: colors.white, fontSize: 29, fontWeight: '800', letterSpacing: -0.8, marginTop: 7 }, cardNote: { color: '#BEE5D8', fontSize: 11, marginTop: 9 }, loading: { alignSelf: 'flex-start', marginTop: 14 }, sectionRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 25 }, section: { color: colors.text, fontSize: 17, fontWeight: '800', letterSpacing: -0.3, marginBottom: 12, marginTop: 25 }, generate: { backgroundColor: colors.primarySoft, borderRadius: 12, paddingHorizontal: 11, paddingVertical: 8 }, add: { color: colors.primary, fontSize: 11, fontWeight: '800' }, account: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: 18, elevation: 2, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: 16, shadowColor: '#193E33', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.05, shadowRadius: 10 }, bank: { color: colors.text, fontSize: 13, fontWeight: '800' }, accountName: { color: colors.muted, fontSize: 10, marginTop: 4, textTransform: 'capitalize' }, number: { color: colors.primaryDark, fontSize: 15, fontWeight: '800' }, emptyCard: { backgroundColor: colors.surface, borderRadius: 18, padding: 20 }, empty: { color: colors.muted, paddingVertical: 12, textAlign: 'center' }, historyCard: { backgroundColor: colors.surface, borderRadius: 18, overflow: 'hidden', paddingHorizontal: 15 }, history: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 14 }, credit: { color: colors.success, fontSize: 12, fontWeight: '800' } });
