<?php

return [
    'Dashboard' => ['dashboard.view'],
    'Users' => ['users.view', 'users.create', 'users.update', 'users.deactivate', 'users.impersonate'],
    'Roles and access' => ['roles.view', 'roles.manage', 'staff.roles.assign'],
    'Transactions' => ['transactions.view', 'transactions.update_status', 'transactions.refund', 'transactions.manual_process'],
    'Funding' => ['funding.view', 'funding.approve', 'funding.reject'],
    'Wallets' => ['wallets.view', 'wallets.credit', 'wallets.debit', 'wallet_logs.view'],
    'Commissions' => ['commissions.view', 'commissions.manage'],
    'Customer retention' => ['followups.view_all', 'followups.view_assigned', 'followups.log_call', 'followups.view_performance'],
    'Account officers' => ['officers.view', 'officers.manage', 'officers.allocate_customers', 'officers.redistribute_customers'],
    'Products' => ['products.view', 'products.create', 'products.update', 'products.delete'],
    'Product categories' => ['product_categories.view', 'product_categories.create', 'product_categories.update', 'product_categories.delete'],
    'Product plans' => ['product_plans.view', 'product_plans.create', 'product_plans.update', 'product_plans.delete', 'product_plans.manage_pricing'],
    'Plan categories' => ['plan_categories.view', 'plan_categories.create', 'plan_categories.update', 'plan_categories.delete'],
    'Custom pricing' => ['custom_pricing.view', 'custom_pricing.manage'],
    'Networks' => ['networks.view', 'networks.create', 'networks.update', 'networks.delete'],
    'Provider automations' => ['automations.view', 'automations.manage', 'automations.credentials_manage'],
    'Reseller plans' => ['reseller_plans.view', 'reseller_plans.create', 'reseller_plans.update', 'reseller_plans.delete'],
    'Bulk data plans' => ['bulk_plans.view', 'bulk_plans.create', 'bulk_plans.update', 'bulk_plans.delete'],
    'Coupons' => ['coupons.view', 'coupons.create', 'coupons.update', 'coupons.delete'],
    'Promotions' => ['promotions.view', 'promotions.manage'],
    'Bonuses' => ['bonuses.view', 'bonuses.manage', 'bonuses.override'],
    'Affiliate finance' => ['affiliate_finance.view', 'affiliate_finance.manage'],
    'Profit reporting' => ['profit.view', 'profit_settings.manage'],
    'Announcements' => ['announcements.view', 'announcements.create', 'announcements.update', 'announcements.delete'],
    'Translations' => ['translations.view', 'translations.manage'],
    'System settings' => ['settings.view', 'settings.manage'],
    'System logs' => ['system_logs.view', 'system_logs.clear'],
];
